# Generated by Django 3.2 on 2023-02-14 09:43

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[users.validators.EmailValidator()], verbose_name='email'),
        ),
    ]
